import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';import vm from 'node:vm';
const out=new URL('../dist/client/',import.meta.url);const script=await readFile(new URL('sw.js',out),'utf8');
async function environment({failInstall=false}={}){
 const handlers={},stores=new Map(),scope='https://example.test/pocket/',prefix='phrase-pocket:'+scope+':';stores.set(prefix+'old',new Map());stores.set('unrelated-app',new Map());
 let online=true;const cacheAPI={async keys(){return[...stores.keys()]},async delete(key){return stores.delete(key)},async open(key){if(!stores.has(key))stores.set(key,new Map());const map=stores.get(key);return{async addAll(requests){const batch=[];for(const req of requests){if(failInstall)throw new Error('Network unavailable');const file=new URL(req.url).pathname.replace('/pocket/','');batch.push([req.url,new Response(await readFile(new URL(file,out)))]);}for(const [url,response]of batch)map.set(url,response);},async match(request){const url=new URL(typeof request==='string'?request:request.url);url.search='';return map.get(url.href)?.clone();}}}};
 const self={registration:{scope},location:new URL(scope+'sw.js'),clients:{async claim(){}},addEventListener:(type,fn)=>handlers[type]=fn};
 vm.runInNewContext(script,{self,caches:cacheAPI,URL,Request,Response,fetch:async()=>{if(!online)throw new Error('Offline');return new Response('network')}});
 async function life(type){let task;handlers[type]({waitUntil:p=>task=p});await task;}
 return{handlers,stores,prefix,life,setOffline(){online=false},async request(path,navigate=false){let task;handlers.fetch({request:{method:'GET',url:new URL(path,scope).href,mode:navigate?'navigate':'cors'},respondWith:p=>task=p});return task;}}
}
test('manifest has iPhone standalone settings and real PNG icons',async()=>{const manifest=JSON.parse(await readFile(new URL('manifest.webmanifest',out),'utf8'));assert.equal(manifest.display,'standalone');assert.equal(manifest.scope,'./');for(const icon of [...manifest.icons,{src:'./icons/apple-touch-icon.png',sizes:'180x180'}]){const buffer=await readFile(new URL(icon.src,out));assert.equal(buffer.subarray(1,4).toString(),'PNG');assert.equal(buffer.readUInt32BE(16),Number(icon.sizes.split('x')[0]));}});
test('complete offline install serves document, code and 115 phrases with network disabled',async()=>{const env=await environment();await env.life('install');await env.life('activate');env.setOffline();assert.match(await(await env.request('./?source=homescreen',true)).text(),/词组口袋/);for(const file of ['app.js','review.js','styles.css','manifest.webmanifest'])assert.ok((await(await env.request(file)).text()).length>20);const data=await(await env.request('phrases.json')).json();assert.ok(data.length>=115);});
test('offline ready signal verifies the cached files',async()=>{const env=await environment();await env.life('install');let task,answer;env.handlers.message({data:{type:'CHECK_OFFLINE'},ports:[{postMessage:value=>answer=value}],waitUntil:p=>task=p});await task;assert.equal(answer.ready,true);});
test('activation deletes only this app scope cache, never other apps',async()=>{const env=await environment();await env.life('install');await env.life('activate');assert.equal(env.stores.has(env.prefix+'old'),false);assert.equal(env.stores.has('unrelated-app'),true)});
test('failed installation preserves previous working cache',async()=>{const env=await environment({failInstall:true});await assert.rejects(env.life('install'));assert.equal(env.stores.has(env.prefix+'old'),true);});
test('built HTML references only local runtime assets',async()=>{const html=await readFile(new URL('index.html',out),'utf8');for(const match of html.matchAll(/(?:src|href)="([^"]+)"/g)){assert.ok(!match[1].startsWith('http'),'Unexpected external runtime dependency');await stat(new URL(match[1],out));}});
