import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {addPhrase,loadState,ratePhrase,pickPhrase,STORAGE_KEY,MIN_WEIGHT,MAX_WEIGHT,parseStored} from '../app/review.js';
const seed=JSON.parse(await readFile(new URL('../app/phrases.json',import.meta.url),'utf8'));
function memory(){const map=new Map();return{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)}}
test('all five images are represented by 115 unique valid entries',()=>{assert.ok(seed.length>=115);assert.deepEqual([1,2,3,4,5].map(p=>seed.filter(x=>Number(x.id.slice(1))<=115&&x.page===p).length),[29,25,26,24,11]);assert.equal(new Set(seed.map(x=>x.english.toLowerCase())).size,seed.length);for(const p of seed){assert.ok(p.chinese&&(!p.source||p.source.startsWith('https://')))}});
test('fresh install loads the seed exactly once across reads',()=>{const s=memory();assert.equal(loadState(s,seed).entries.length,seed.length);assert.equal(loadState(s,seed).entries.length,seed.length)});
test('forget and remember persist opposite weight changes after reopening',()=>{const s=memory();ratePhrase(s,seed,'p001','forgot');assert.equal(loadState(s,seed).entries[0].weight,2);ratePhrase(s,seed,'p001','remember');ratePhrase(s,seed,'p001','remember');assert.equal(loadState(s,seed).entries[0].weight,.5)});
test('weights remain bounded with no permanent removal',()=>{const s=memory();for(let i=0;i<100;i++)ratePhrase(s,seed,'p001','remember');assert.equal(loadState(s,seed).entries[0].weight,MIN_WEIGHT);for(let i=0;i<100;i++)ratePhrase(s,seed,'p001','forgot');assert.equal(loadState(s,seed).entries[0].weight,MAX_WEIGHT)});
test('sampling follows relative weights and excludes current card',()=>{const entries=[{id:'a',weight:1},{id:'b',weight:3}];let b=0;for(let i=0;i<10000;i++)if(pickPhrase(entries,null,()=>i/10000).id==='b')b++;assert.equal(b,7500);for(let i=0;i<100;i++)assert.equal(pickPhrase(entries,'b').id,'a')});
test('empty and one-item sets are safe',()=>{assert.equal(pickPhrase([]),null);assert.equal(pickPhrase([{id:'a',weight:1}],'a').id,'a')});
test('adding saves user input, preserves feedback, and detects duplicates',()=>{const s=memory();ratePhrase(s,seed,'p001','forgot');addPhrase(s,seed,'  zz test phrase one  ','记住；牢记','u-test');const loaded=loadState(s,seed);assert.equal(loaded.entries.length,seed.length+1);assert.equal(loaded.entries[0].weight,2);assert.equal(loaded.entries.at(-1).english,'zz test phrase one');assert.throws(()=>addPhrase(s,seed,'ZZ   TEST PHRASE ONE','重复','u-other'),/已经/);assert.throws(()=>addPhrase(s,seed,'   ','释义','u-empty'),/不能为空/)});
test('invalid or future data is never silently overwritten',()=>{const s=memory();s.setItem(STORAGE_KEY,'broken');assert.throws(()=>ratePhrase(s,seed,'p001','forgot'));assert.equal(s.getItem(STORAGE_KEY),'broken');assert.throws(()=>parseStored(JSON.stringify({version:2,custom:[],weights:{}})));assert.throws(()=>parseStored(JSON.stringify({version:1,custom:[],weights:{p001:-1}})))});
test('storage quota failure reports failure and preserves previous data',()=>{const s=memory();addPhrase(s,seed,'zz test phrase two','暂时','u-one');const previous=s.getItem(STORAGE_KEY);s.setItem=()=>{throw new Error('quota')};assert.throws(()=>ratePhrase(s,seed,'p001','forgot'),/未能保存/);assert.equal(s.getItem(STORAGE_KEY),previous)});
test('updates reread storage so sequential tabs do not discard changes',()=>{const s=memory();loadState(s,seed);addPhrase(s,seed,'zz test phrase three','终于','u-new');ratePhrase(s,seed,'p001','forgot');assert.equal(loadState(s,seed).entries.length,seed.length+1)});
test('seed corrections merge without resetting learning weights',()=>{const s=memory();ratePhrase(s,seed,'p001','forgot');const next=seed.map(x=>x.id==='p001'?{...x,chinese:'更新后的释义'}:x);assert.equal(loadState(s,next).entries[0].chinese,'更新后的释义');assert.equal(loadState(s,next).entries[0].weight,2)});
test('unexpected feedback and missing id leave storage unchanged',()=>{const s=memory();assert.throws(()=>ratePhrase(s,seed,'p001','bad'));assert.throws(()=>ratePhrase(s,seed,'missing','forgot'));assert.equal(s.getItem(STORAGE_KEY),null)});
